### ISSUE TITLE
Tasmota ws2812b on different pins.

### ISSUE THREAD

**Issue by medjaiiii** [arendst/Tasmota#10924]
Hi everyone, need some help. I want esp8266 to manage two different ws2812b tapes. In fact, the tape is one or two LEDs, but it is necessary to control them separately. I want to make signs over the toilet and bathroom(free\occupied). Mqtt is important. But when you select the ws2812b configuration for different pins, it does not allow you to manage them, only one. How to solve it?
![2021-02-11 23_17_39-Window](https://user-images.githubusercontent.com/54689409/107693693-83c1c680-6cbf-11eb-943e-496919295bf7.png)
![2021-02-11 23_17_58-Window](https://user-images.githubusercontent.com/54689409/107693695-845a5d00-6cbf-11eb-8252-b832e24de0a9.png)

**Comment by ascillato** [comment]
Hi,

Sorry, that is not supported due to you can put all your leds on the same line and control them independently using Tasmota commands as explained in the docs and in old issues.

If you need further assistance, please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md)

Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
