### ISSUE TITLE
Connect device with application eWeLink

### ISSUE THREAD

**Issue by ngokhachung1998** [arendst/Tasmota#11226]
I want to connect ESP8266 with application eWeLink. I have tried but  failed. Can you have me

**Comment by ascillato** [comment]
Tasmota won't connect to ewelink. Not supported

**Comment by ngokhachung1998** [comment]
> Tasmota won't connect to ewelink. Not supported

Do you know any software similar to ewelink? Ewelink made it a bit easy for me to configure the device

**Comment by ascillato** [comment]
Ewelink is a software from iTead for using the original firmware of sonoff devices. It is cloud based and not related and not compatible with Tasmota. 

If you haven't flashed Tasmota on your device, you can use ewelink.

If you have flashed Tasmota in your device, ewelink is not going to work anymore due to Tasmota won't use iTead Cloud Servers.

If you need a software to manage your Tasmotas, please check the Tasmota docs for TDM (Tasmota Device Manager), TasmoAdmin and others.

**Comment by ascillato** [comment]
If you need further assistance, please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md)

Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
