### ISSUE TITLE
3 shutters detected on a Sonoff 4chpro configured for 2. Using HA and new Tasmota integration.

### ISSUE THREAD

**Issue by JackTalisker** [arendst/Tasmota#11710]
Seems that Tasmota discovery topic sends null values after Shutter1 and Shutter2. After that a useless "Shutter3" appears.

Here is the discovery config topic:
`{"ip":"192.168.0.80","dn":"4CHpro_serr","fn":["SerrSala1_1","SerrSala1_2","SerrSala2_1","SerrSala2_2",null,null,null,null],"hn":"4CHpro_serr-1529","mac":"1234567890","md":"Sonoff 4CH Pro","ty":0,"if":0,"ofln":"Offline","onln":"Online","state":["OFF","ON","TOGGLE","HOLD"],"sw":"9.3.1.2","t":"4CHpro_serr","ft":"%prefix%/%topic%/","tp":["cmnd","stat","tele"],"rl":[3,3,3,3,0,0,0,0],"swc":[-1,-1,-1,-1,-1,-1,-1,-1],"swn":[null,null,null,null,null,null,null,null],"btn":[0,0,0,0,0,0,0,0],"so":{"4":0,"11":0,"13":0,"17":0,"20":0,"30":0,"68":0,"73":0,"82":0,"114":0,"117":0},"lk":1,"lt_st":0,"sho":[4,4,0,0],"ver":1}`

**Comment by ascillato** [comment]
Please, could you be so kind on completing the [troubleshooting template](https://github.com/arendst/Tasmota/issues/new/choose) in order to have more information so as to properly help you?

Remember to read the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information 
See [Docs](https://tasmota.github.io/docs/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
