### ISSUE TITLE
Cross-site scripting vulnerability

### ISSUE THREAD

**Issue by TheRabbitX** [arendst/Tasmota#12220]
I've identified a Cross-site scripting vulnerability (XSS) in the web interface of Tasmota 6.5.0. Unfortunately, I can not check if the current release is also affected. It would be nice if someone could check this out and give me feedback.

Navigate to "Configuration" - "Configure Other" and insert the following sting in the field "Friendly Name 1":
"/><script>alert(1)</script>

After that, a JavaScript alert box should appear if the version is vulnerable.

**Comment by s-hadinger** [comment]
It's fixed for friendly name, but still the case for device name. However it's a desirable feature to allow html in the name so you can customize the appearance if you want. 

The risk is very low since you can onky attack yourself on a device that you already control. I don't see any security issue here. Am I missing something?
