### ISSUE TITLE
Tasmota32 KNX section 

### ISSUE THREAD

**Issue by noroozihossein** [arendst/Tasmota#13605]
Hello dear guys first of all many thank's to developing Tasmota 
as i use usually Tasmota KNX and other devices with KNX protocol to control Tasmota module's i use ESP8266 Tasmota KNX version normally without any problem just send one time telegram to get telegram in Tasmota side and act but in Tasmota ESP32 i tested and used several modules in KNX section you should send several times telegram to get and act in Tasmota32 side 
could you please check and confirm the problem it seems there is a issue in Tasmota32 KNX driver side
thank you in advance

**Comment by ascillato** [comment]
Hi, Sorry I didn't saw your issue before, as it has been auto closed due to the template was deleted.

KNX on ESP32 is working fine. Please, check your network, your RSSI, your multicast settings in your router, the amount of devices you have (more than 30 you need a very good router or add more APs), etc.
