### ISSUE TITLE
switchmode 5 dosn't work

### ISSUE THREAD

**Issue by Papablaubaer** [arendst/Tasmota#14839]
I want to perform an action every time a switch opens, also I want to perform a different action when the switch is held down longer. Switchmode 5 seems to do just that.

In fact, Tasmota sends "hold" when the input is briefly high and immediately low again. If an impulse is executed twice, Tasmota first sends toogle then hold.

Is there an error in the program or am I thinking wrong?

**Comment by barbudor** [comment]
It mainly depends on the cabling and the default state
The doc says
> SwitchMode 5
Set push-button with long press mode (0 = TOGGLE, 1 = ON (default), long press = HOLD)

If you connect the switch normally-open (aka push-to-make) between GND and GPIO, by default, GPIO is in the default state HIGH due to internal pull-up.
Pressing the switch connect GPIO to GND.
If releasing immediatly, Tasmota will send TOGGLE
If maintain > 4sec, Tasmota will send HOLD
Switch needs then to go back to stand-by (open) and GPIO Is back to high level due to internal pull-up
