### ISSUE TITLE
DS3231 Tasmota Incorrect year

### ISSUE THREAD

**Issue by gfn256** [arendst/Tasmota#17799]
I checked the time/date set by Tasmota on the RTC and all is correct, except for the year being 2053 instead of 2023.
I know Tasmota is very advanced and ahead of its time, but 30 years is a bit much!!
I'm guessing that this is caused by Tasmota's assumption that the zero setting of the RTC is 1970.  In fact todays RTC chips use the year 2000, this would probably explain the discrepancy.

**Comment by barbudor** [comment]
I will have a look tonight

**Comment by sfromis** [comment]
Maybe this is somehow the upcoming [Y2K38](https://en.wikipedia.org/wiki/Year_2038_problem) trouble popping up? Year 2023 is 15 years before the Unix timestamp rollover, and 2053 is 15 years after the Epochalypse.

**Comment by barbudor** [comment]
So indeed I can see that tasmota is breaking the `time_t` epoch into an almost standard `struct tm` except that the `tm.year` field in giving the number of years from 1970 instead of the standard full 4-digit year.
So what gets written in the register is that value : (this year - 1970)
As well the `century bit` is not set

There is indeed a risk Feb 28th or a Feb 29th (depending of the year) as the chip may not calculate correctly the leap year.

So probably best to set correctly the century bit and shift the year correctly.
