### ISSUE TITLE
Can't Upgrade ESP32

### ISSUE THREAD

**Issue by marcolino7** [arendst/Tasmota#19096]
Hi,
I am running version 10.1.0(tasmota) on a ESP32.
When I try to Upgrade I get Not Enough Space message.
I use this file for upgrade: http://ota.tasmota.com/tasmota32/release/tasmota32.bin
This is the memory of My ESP32:
![image](https://github.com/arendst/Tasmota/assets/11460036/ed85eb8c-17f8-411f-9257-fdc87bde3a76)

I tried looking around but I cannot find suitable info, some help would be appreciated.

Regards

Marco

**Comment by mkjustuk** [comment]
On ESP8266 devices, you can choose a compressed option which is smaller.  I don't see that for the ESP32 binaries (most likely because the assumption is the 4mb is plenty).

Try downloading the file in your upgrade URL, compressing it and the locally upgrade using the compressed version.

To compress, you're looking to get a .gz (gzip) file, so for instance:
[https://linhost.info/2012/08/gzip-files-in-windows/#:~:text=Gzip%20Single%20File,on%20OK%20to%20start%20compressing.]

**Comment by arendst** [comment]
Won't work on ESP32 as we do not support zipped binaries.

Follow the recommended upgrade path and use the partition wizard. See https://github.com/arendst/Tasmota/discussions

**Comment by sfromis** [comment]
> Try downloading the file in your upgrade URL, compressing it and then locally upgrade using the compressed version.

NO.

When compressed files are relevant, Tasmota already provides them. And this indeed not the case for ESP32.
