### ISSUE TITLE
Gosund SP111 - new 15A (3450W max) version - no power measuring values

### ISSUE THREAD

**Issue by FUSiiiiON** [arendst/Tasmota#6845]
It seems that the Gosund SP111 got a new Revision, because I got recently 4 devices of a 15A version (3450W max) instead the 10A version. I also already own the Gosund SP111 10A version, where everything is working fine with the BlitzWolf SHP (45) template.

But the BlitzWolf template does not work completely with the 15A version, because it does only show the values for Energy Today / Energy Yesterday and Energy Total. Voltage, Current, Power and all the other power measuring values are 0.

On the left is the 15A version (the washing machine was on at that time).. on the right the 10A version of the SP111 with the BlitzWolf SHP (45) configuration:
![Bildschirmfoto 2019-11-05 um 21 26 13](https://user-images.githubusercontent.com/57416560/68243503-ee8f4700-0012-11ea-9ce5-d2a59c820645.png)

I flashed all of my four 15A devices with the same result.

Does anybody has already got the 15A version of the Gosund SP111 and know the correct GPIO values/assignments to get the missing power informations?

![WhatsApp Image 2019-11-05 at 21 38 27](https://user-images.githubusercontent.com/57416560/68244293-cf91b480-0014-11ea-97c4-0717270a9e72.jpeg)
![WhatsApp Image 2019-11-05 at 21 38 26](https://user-images.githubusercontent.com/57416560/68244294-d02a4b00-0014-11ea-8017-e54657e2d547.jpeg)
![WhatsApp Image 2019-11-05 at 21 38 26(1)](https://user-images.githubusercontent.com/57416560/68244295-d02a4b00-0014-11ea-956b-b4110d521b09.jpeg)

**Comment by cavac** [comment]
I just got mine an hour ago. Where did you find IO0 and GND? Or did you flash OTA?

**Comment by FUSiiiiON** [comment]
I flashed the device via OTA

**Comment by cavac** [comment]
Tuya convert?

**Comment by FUSiiiiON** [comment]
Yes

**Comment by FUSiiiiON** [comment]
BTW: I just recognized, that this topic would be better posted in the forum instead as an issue for Tasmota itself. I hope it is not a problem. Next time i open up a topic in the forum.

**Comment by Jason2866** [comment]
@FUSiiiiON  Exactly😀 please close
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by Viech83** [comment]
I had the same problem.
Insert this as Template
{"NAME":"Gosund SP111 V","GPIO":[57,255,56,255,132,134,0,0,131,17,0,21,0],"FLAG":0,"BASE":45}

**Comment by komw** [comment]
> I had the same problem.
> Insert this as Template
> {"NAME":"Gosund SP111 V","GPIO":[57,255,56,255,132,134,0,0,131,17,0,21,0],"FLAG":0,"BASE":45}

Are you sure that is working for SP111? I still have: 
"
Voltage | 0 V
-- | --
0.000 A
0 W
0 VA
0 VAr
0.00
0.033 kWh
0.000 kWh
0.033 kWh
"

**Comment by taste66** [comment]
I use this for the BW-SHP6 3450W which is internally the same
Red LED when on
`{"NAME":"BW-SP6 15A","GPIO":[56,255,158,255,132,134,0,0,131,17,0,21,0],"FLAG":0,"BASE":45}`
Blue LED when on
`{"NAME":"BW-SP6 15A","GPIO":[158,255,56,255,132,134,0,0,131,17,0,21,0],"FLAG":0,"BASE":45}`

**Comment by Viech83** [comment]
Hi !yes, it is working well at all my 8 SP111.Can you send me a screenshot from your template (how you Insert this in the device?)Kind Regards,Philipp LenzVon meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Szymon Gładysz <notifications@github.com> Datum: 28.01.20  21:47  (GMT+01:00) An: arendst/Tasmota <Tasmota@noreply.github.com> Cc: Viech83 <Philipp_lenz@t-online.de>, Comment <comment@noreply.github.com> Betreff: Re: [arendst/Tasmota] Gosund SP111 - new 15A (3450W max) version - no
  power measuring values (#6845) 
I had the same problem.
Insert this as Template
{"NAME":"Gosund SP111 V","GPIO":[57,255,56,255,132,134,0,0,131,17,0,21,0],"FLAG":0,"BASE":45}

Are you sure that is working for SP111? I still have:
"
Voltage | 0 V
-- | --
0.000 A
0 W
0 VA
0 VAr
0.00
0.033 kWh
0.000 kWh
0.033 kWh
"

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/arendst/Tasmota/issues/6845?email_source=notifications\u0026email_token=ANWWYEYSTDRD54CEPEG2AOLRACKXDA5CNFSM4JJIISJ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKE24NY#issuecomment-579448375",
"url": "https://github.com/arendst/Tasmota/issues/6845?email_source=notifications\u0026email_token=ANWWYEYSTDRD54CEPEG2AOLRACKXDA5CNFSM4JJIISJ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKE24NY#issuecomment-579448375",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Viech83** [comment]
Just copied from one of my device:{"NAME":"Gosund SP111 V","GPIO":[57,255,56,255,132,134,0,0,131,17,0,21,0],"FLAG":0,"BASE":45}Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Szymon Gładysz <notifications@github.com> Datum: 28.01.20  21:47  (GMT+01:00) An: arendst/Tasmota <Tasmota@noreply.github.com> Cc: Viech83 <Philipp_lenz@t-online.de>, Comment <comment@noreply.github.com> Betreff: Re: [arendst/Tasmota] Gosund SP111 - new 15A (3450W max) version - no
  power measuring values (#6845) 
I had the same problem.
Insert this as Template
{"NAME":"Gosund SP111 V","GPIO":[57,255,56,255,132,134,0,0,131,17,0,21,0],"FLAG":0,"BASE":45}

Are you sure that is working for SP111? I still have:
"
Voltage | 0 V
-- | --
0.000 A
0 W
0 VA
0 VAr
0.00
0.033 kWh
0.000 kWh
0.033 kWh
"

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/arendst/Tasmota/issues/6845?email_source=notifications\u0026email_token=ANWWYEYSTDRD54CEPEG2AOLRACKXDA5CNFSM4JJIISJ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKE24NY#issuecomment-579448375",
"url": "https://github.com/arendst/Tasmota/issues/6845?email_source=notifications\u0026email_token=ANWWYEYSTDRD54CEPEG2AOLRACKXDA5CNFSM4JJIISJ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKE24NY#issuecomment-579448375",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by komw** [comment]
Ah,, I forgot to tick "activate"... but still I need to calibrate it, because it shows me a 280V (instead od 240V)

**Comment by Viech83** [comment]
Yes, calibration is needed.Best you first calibrate the voltage and then the power.    Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Szymon Gładysz <notifications@github.com> Datum: 28.01.20  23:36  (GMT+01:00) An: arendst/Tasmota <Tasmota@noreply.github.com> Cc: Viech83 <Philipp_lenz@t-online.de>, Comment <comment@noreply.github.com> Betreff: Re: [arendst/Tasmota] Gosund SP111 - new 15A (3450W max) version - no
  power measuring values (#6845) Ah,, I forgot to tick "activate"... but still I need to calibrate it, because it shows me a 280V (instead od 240V)

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/arendst/Tasmota/issues/6845?email_source=notifications\u0026email_token=ANWWYE2ITFNGL7YHW3LWMY3RACXO7A5CNFSM4JJIISJ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKFG5FI#issuecomment-579497621",
"url": "https://github.com/arendst/Tasmota/issues/6845?email_source=notifications\u0026email_token=ANWWYE2ITFNGL7YHW3LWMY3RACXO7A5CNFSM4JJIISJ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKFG5FI#issuecomment-579497621",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
