### ISSUE TITLE
SetOption68 1 Channel control not working when using only one channel

### ISSUE THREAD

**Issue by Povilas1** [arendst/Tasmota#6990]
PWM Dimmer does not work when setting Option68 to 1 and only one PWM output enabled. I can only on / off, but no channel control when enabled only one PWM output with no relays.

21:37:14 CMD: Channel1 50
21:37:14 RSL: stat/sonoff/RESULT = {"POWER1":"ON","Channel1":100,"Color":"FF"}

**Comment by s-hadinger** [comment]
I don't dare asking why you want SetOption68 1 with only one channel. 

I will take a look.

**Comment by ascillato2** [comment]
SetOption68 is for Multi-channel PWM.

Please, could you be so kind on completing the [troubleshooting template](https://github.com/arendst/Sonoff-Tasmota/issues/new/choose) in order to have more information so as to properly help you?

Remember to read the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by Povilas1** [comment]
Currently my ESP is wired to only one light. Today I discovered in Option68 and wanted to try it out before making any changes to the hardware side :D

**Comment by ascillato2** [comment]
Which Tasmota version are you using?

**Comment by Povilas1** [comment]
@ascillato2 Sonoff-Tasmota 6.7.1

**Comment by ascillato2** [comment]
ah, ok, would you be able to test on latest version from development branch: http://thehackbox.org/tasmota/tasmota.bin ? Thanks

**Comment by s-hadinger** [comment]
Fixes in #7020
