### ISSUE TITLE
Sonoff Touch T1 periodically auto power on and off

### ISSUE THREAD

**Issue by deadstar2009** [arendst/Tasmota#6996]
There is a bug in Sonoff Touch T1 on latest Tasmota 6.7.1 firmware. Periodically (5-30 min) device auto power on internal rele (as if a touch sensor). After another 5-30 min (rele is on) device powered off rele.
For the test, i changed module configuration to sonoff basic, but it still keeps turning on and off automatically.

**Comment by ascillato2** [comment]
Hi,

That can be due to ghost switching (hardware related, wires, and how are they connected) or retained messages in your mqtt broker. Please, search for solutions in the wiki and in issues. This was addressed several times before.

If after that, you can't solve your issue, please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
