### ISSUE TITLE
After update to 7.1 always reconnect

### ISSUE THREAD

**Issue by tuffig** [arendst/Tasmota#7069]
After upgrading a sonoff Touch T1 from 6.7.1 to 7.1.0 
the device logs in about every 30 seconds. 
WIF: Connecting to AP1 xxx in mode 11N as xxxxxx
I resetted the device but same problem and with or without MQTT

**Comment by ascillato** [comment]
Please, could you be so kind on completing the [troubleshooting template](https://github.com/arendst/Sonoff-Tasmota/issues/new/choose) in order to have more information so as to properly help you?

Or you can also address this to the Tasmota support chat if you prefer. 

Remember to read the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
