### ISSUE TITLE
Additional stop command argument for "shutterposition1 *" 

### ISSUE THREAD

**Issue by HGBAXXTER** [arendst/Tasmota#7369]
**Have you looked for this feature in other issues and in the docs?**  
Yes

**Is your feature request related to a problem? Please describe.**  
Feature is requested for better compatibility with OpenHAB MQTT binding

**Describe the solution you'd like**  

Currently, the "shutterposition1 *" MQTT command allows only numerical values between 0 and 100. It could be beneficial however, to also allow "STOP" as a string argument for "shutterposition1 *" to interrupt the movement.

**Describe alternatives you've considered**  
Using "ShutterStop" is of course always possible, but some home automation services may require the same MQTT topic for all commands for one channel (e.g. in my case the OpenHAB 2.5 MQTT binding).

**Additional context**  
None

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by meingraham** [comment]
Depending on which version of the MQTT binding, you can add multiple Items (`mqtt1`) or multiple Thing Channels (linked to respective Items) for each Tasmota command needed. Your .rules logic can select the right Item to `.sendCommand`.

`STOP` is an action, not a position. Mixing this option into the position command syntax is anti-intuitive.

Since you are using a home automation hub, that is able easily to handle your need and it does not burden Tasmota with additional code.

If you have additional questions, please address this to the [Tasmota Support Discord Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are best used for Tasmota **_software feature requests and bug reporting_**. Troubleshooting and setup assistance is more effective using an interactive forum.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://tasmota.github.io/docs/#/Home) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
