### ISSUE TITLE
List of safe devices to be used with sensors ( With & Without power measurement) 

### ISSUE THREAD

**Issue by seritos** [arendst/Tasmota#7710]
**Have you looked for this feature in other issues and in the docs?**  
Yes

**Is your feature request related to a problem? Please describe.**  
It is clearly unsafe to connect sensors to a non-isolated devices and sometimes unknown in the rest. 

**Describe the solution you'd like**  
Describe the tests we could perform to ensure that the device is safe

**Describe alternatives you've considered**  
Use only low voltage devices. 

**Additional context**  
Discussed in: 
https://github.com/arendst/Tasmota/issues/920
https://github.com/arendst/Tasmota/issues/1941
https://github.com/arendst/Tasmota/issues/4732

**(Please, remember to close the issue when the problem has been addressed)**  

Hi All,

As the use of of sensor has become more and more popular with the time, I believe its quite useful and interest make sure that the devices we are using are safe to be used with sensors. 

It is known that devices that do not include power measurement are reasonable safe, however devices WITH power management are unsafe to use with sensors because the mains is not properly isolated, and therefore we could find hi-voltage in the esp pins. 

As there are dozens of different models in the market. I would like to purpose a shared list of devices that are connected to mains and are safe to use with sensors and also the analysis being take to determine that the device in concrete is safe. 

So, as far as I know, the Sonoff S20 is safe, as it is isolated and POW is NOT.

The test to determinate it could be to measure the voltage between the Mains and 3,3/GND of the esp and make sure is 0 volts. 

I could check it with the Sonoff Touch EU and UK version, and with the AWP07L (this one has PM and it is said that is isolated, although I haven't test it.)

Thanx!

**Comment by ascillato2** [comment]
Hi,

Thanks for sharing your ideas. 

So far, most of the power measurement devices are not isolated because it is cheaper in that way and the manufacturers don't have designed those devices for sensors' support.

Making a list is a good idea but it is going to be super short because most of those can't be used with sensors. So it is better to add the information for each device on the template repository.

Also, we don't want to confuse users. Mainly, the new ones and the ones that don't have knowledge on how to modify devices that are connected to mains. As you know, it is not safe to modify devices that were not designed for sensors by enthusiasts that don't have an electrical background.

As explained in the Tasmota docs, for sensors it is recommended to use safer devices that were meant for sensors like a nodemcu.

Thanks
