### ISSUE TITLE
homebridge-hue support doesn't seem to work after updating to 8.1.0

### ISSUE THREAD

**Issue by suhajda3** [arendst/Tasmota#7827]
### PROBLEM DESCRIPTION
I have updated all my Sonoff-Tasmota devices (Sonoff Basic Module) from version 6.7.1 to 8.1.0 (first updating to 7.2.0 and then to 8.1.0). Before the update all my Sonoff devices worked great with [homebridge-hue](https://github.com/ebaauw/homebridge-hue) but after the update they stopped working.

Even when downgrading a device to 6.7.1 (and resetting the configuration) it still doesn't seem to work. It works with Alexa without a problem. You can find more information on [this ](https://github.com/ebaauw/homebridge-hue/issues/640)issue.

### REQUESTED INFORMATION
- [x] Device used (e.g., Sonoff Basic): Sonoff Basic
- [X] Tasmota binary firmware version number used: 8.1.0

### TO REPRODUCE
Enable Hue emulation on Tasmota 8.1.0 and try to retrieve paths with [homebridge-hue](https://github.com/ebaauw/homebridge-hue) ph command (Command line interface to Philips Hue API.):
```
# ph -H 192.168.99.12 -u api get /
[
  {
    "success": {
      "username": "cc6368"
    }
  }
]
```

### EXPECTED BEHAVIOUR
The paths should appear.

### SCREENSHOTS
n/a

### ADDITIONAL CONTEXT
Based on the information I have provided @ebaauw thinks (he doesn't have a device to test on so he is solely relying on my output) Tasmota mistakingly handles GET / as POST /.

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Hi, please complete the template in order to have more debug information so as to properly help you. Thanks

**Comment by suhajda3** [comment]
I have updated the template. Thanks

**Comment by Jason2866** [comment]
Tasmota does support only Alexa hardware. The fact that homebridge-hue worked before was luck.
It seems that the setup with 6.7.1. was not stable too because reverting back to this version
does not bring back the functionality.
Sorry no issue, since it was never supported.
You are welcome to submit a PR to support homebridge-hue since it seems it needs just
a few adaptions to get it running.
The main contributors will NOT do since no one uses homebridge-hue.

**Comment by ebaauw** [comment]
> The fact that homebridge-hue worked before was luck.

Not quite, see https://github.com/ebaauw/homebridge-hue/issues/512.

The issue seems to be that with the newer firmware, the request to get the full state (GET /api/username) seems to be broken; the response looks like the response to a request to create a user (POST /api).  See https://github.com/ebaauw/homebridge-hue/issues/640.

**Comment by Jason2866** [comment]
So if i get your statement correct, time to close this issue.

**Comment by suhajda3** [comment]
> So if i get your statement correct, time to close this issue.

Could we wait until the issue is actually resolved? ;-)

(If the problem is on homebridge-hue side I will close this issue, but if it's on Tasmota side it would be great to excalate it.)

**Comment by Jason2866** [comment]
Okay leave it open for reference

**Comment by suhajda3** [comment]
@ebaauw confirmed that this problem is on the homebridge-hue side so I will close this issue now.

@Jason2866 could you please delete [this](https://github.com/arendst/Tasmota/issues/7826) issue. It is a duplicate of this one. Thanks
