### ISSUE TITLE
turn on/off pir with sun setting

### ISSUE THREAD

**Issue by Vingen168** [arendst/Tasmota#8053]
Hi, i have this settings is my sonoff basic

a mini pir sensor connected to GPIO1 config as Switch1n(82)

with these  rules
`switchmode1 1`
`rule1 on switch1#state do publish hallen/pir/RADAR1/%value% endon`
`rule2 on switch1#state=1 do backlog power1 on; ruletimer1 60 endon on rules#timer=1 do power1 off endon`

everything work fine, the light turns off when no motion is detected after 60 sec.
but i need a rule to turn off the pir sensor base on sun settings, sunrise=off, sunet=on 

i've tried the cookbook rules, and it didnt work. 

and i tired this 
`rule3 on Switch1#state=1 do backlog event checksunrise=%time%; event checksunset=%time% endon on event#checksunrise<%sunrise% do rule1 0 endon on event#checksunset>%sunset% do rule1 1 endon; on event#checksunrise<%sunrise% do rule2 0 endon on event#checksunset>%sunset% do rule2 1`

no luck so far.
Can anyone guide me how it suppose to be done?

/thanks.

**Comment by ascillato** [comment]
Hi, instead of those rules, you can use the ones of the example of PIR and sun in the docs. Using Rule1 1 in an everyday basis will produce more unnecessary writings on the flash, degrading it. Better is the example of the docs.

If you need further assistant on Tasmota usage, please address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
