### ISSUE TITLE
SONOFF D1 USE KNX.bin，Dimming channel is not configured，NO 1BYTE configured,Only 1bit switch channel....

### ISSUE THREAD

**Issue by DONGFENG13** [arendst/Tasmota#8084]
**Have you looked for this feature in other issues and in the docs?**  

**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**  
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
Our ability to provide assistance is greatly hampered since you did not take a few minutes to complete the [troubleshooting template](https://github.com/arendst/Sonoff-Tasmota/issues/new/choose) with the requested information. The details requested potentially affect which options to pursue. The small amount of time you spend completing the template will also help the volunteers providing the assistance to you to reduce the time required to help you.

Please close this issue and address this to the [Tasmota Support Discord Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are best used for Tasmota **_software feature requests and bug reporting_**. Troubleshooting and setup assistance is more effective using an interactive forum.
 
Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).
 
Thanks.
 
### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by ascillato2** [comment]
Adding this request to **_RGB with KNX #7438_** due adding that will add this feature too.

**Comment by DONGFENG13** [comment]
I don't know how to operate



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Adrian Scillato"<notifications@github.com&gt;; 
发送时间: 2020年4月7日(星期二) 凌晨0:54
收件人: "arendst/Tasmota"<Tasmota@noreply.github.com&gt;; 
抄送: "东风破"<83507451@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [arendst/Tasmota] SONOFF D1 USE KNX.bin，Dimming channel is not configured，NO 1BYTE configured,Only 1bit switch channel.... (#8084)





 
Adding this request to RGB with KNX #7438 due adding that will add this feature too.

**Comment by ascillato** [comment]
Sorry, It is not implemented yet. Your requets has been added to the list of features to be added. As your request is going to be a part of another request, you can follow the advance of development on the issue #7438
