### ISSUE TITLE
Hue Link Button

### ISSUE THREAD

**Issue by ReEg010** [arendst/Tasmota#8716]
**Have you looked for this feature in other issues and in the docs?**
Yes

**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._
Some hue enabled devices require a link button response from the hue emulation

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._
A simple push button on the web interface to simulate hue link button press

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._
diyHue - not compatible with tasmota

**Additional context**  
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Hi,

You are using https://github.com/diyhue/diyHue right?

From the comment of one of their issues ( https://github.com/diyhue/diyHue/issues/410#issuecomment-644612425 ):

> Hue apps will allow only supported entertainment lights to be added. ESPHome use custom modelid, and firmware version, so these must be replaced.

So, it can be seen that the problem is that ESPHome and Tasmota as well, they identify **in the network** as custom devices and they are not emulating a bulb.

There is no need of adding any button due to the link on Hue protocol is automatic by UDP.

So, please, open an issue on [diyhue](https://github.com/diyhue/diyHue/issues), to allow support of Custom firmwares like Tasmota. Thanks.
