### ISSUE TITLE
Request for I2C PCF8591T Analog Input/Output

### ISSUE THREAD

**Issue by gamer123** [arendst/Tasmota#8871]
**Have you looked for this feature in other issues and in the docs?**  
Yes.
**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._
No.
**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._
Add I2C device to the code.
**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**  
_Add any other context or screenshots about the feature request here._
I  add the link of datasheet
https://www.nxp.com/docs/en/data-sheet/PCF8591.pdf

4 analog Input
1 analog Output
here is a C++ libary for  PCF8591 may it helps.
https://github.com/xreef/PCF8591_library
Adress:

(I2C addresses 0x48 - 0x4F)

But there is already a sensor with this adress. Is this a problem ? 

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Kunzol** [comment]
I just added a pcf8591 to my ESP01 with tasmota. 
As the address is 0x48, it is automatically detected as ADS1115 and it delivers data.
But as ADS1115 is 16 bit and pcf8591 is only 8 bit, the data shown is negative and looks semi-random. 
Which is not surprising, because the ADS1115 writes 2 times 8 bit to the bus on read request, while PCF8591 only answers one 8bit. Maybe the single 8 bit answer is read two times. 

Additionally I tried to change the address by removing A2 from GND and attach A2 to VDD. 
With `I2Cscan` it returns the address 0x4c, which is detected as "DS1624-4" (Temperature sensor). 

Okay, I did this just to play a bit. The outcome was clear before I started.

Conclusion is, there are many I2C devices with the same address (no IANA which  assignes the numbers). 
If autodetection should work for devices with same address, there must be an additional selector. 
Easiest is to build a Tasmota binary containing only the drivers you want to use.
